In [55]:
import pandas as pd
import numpy as np

In [21]:
demand_driving = pd.read_csv('demand_driving_MWh.tsv', sep='\t', header=None)

In [22]:
demand_driving

               0         1
0         0.NO03  0.000147
1         1.NO03  0.000147
2         2.NO03  0.000146
3         3.NO03  0.000147
4         4.NO03  0.000147
...          ...       ...
96355  8755.NO54  0.000249
96356  8756.NO54  0.000210
96357  8757.NO54  0.000179
96358  8758.NO54  0.000151
96359  8759.NO54  0.000138

[96360 rows x 2 columns]

In [23]:
demand_driving['zone'] = demand_driving[0].str[-4:]
demand_driving['hour'] = demand_driving[0].str[:-5]
demand_driving = demand_driving.drop(columns=[0]).rename(columns={1:'value'})

In [24]:
demand_driving

          value  zone  hour
0      0.000147  NO03     0
1      0.000147  NO03     1
2      0.000146  NO03     2
3      0.000147  NO03     3
4      0.000147  NO03     4
...         ...   ...   ...
96355  0.000249  NO54  8755
96356  0.000210  NO54  8756
96357  0.000179  NO54  8757
96358  0.000151  NO54  8758
96359  0.000138  NO54  8759

[96360 rows x 3 columns]

In [68]:
avg = {}
for i in demand_driving.zone.unique():
    avg[i] = (demand_driving[demand_driving.zone == i].value.sum()/365).round(6)

In [76]:
np.mean(list(avg.values()))*1000 #kWh

6.363818181818181