In [26]:
import pandas as pd

In [27]:
demand_driving = pd.read_csv('demand_driving.tsv', sep='\t', header=None)

In [28]:
demand_driving

               0         1
0         0.NO03  0.000019
1         1.NO03  0.000013
2         2.NO03  0.000006
3         3.NO03  0.000013
4         4.NO03  0.000000
...          ...       ...
96355  8755.NO54  0.000206
96356  8756.NO54  0.000150
96357  8757.NO54  0.000081
96358  8758.NO54  0.000037
96359  8759.NO54  0.000019

[96360 rows x 2 columns]

In [29]:
demand_driving['zone'] = demand_driving[0].str[-4:]
demand_driving['hour'] = demand_driving[0].str[:-5]
demand_driving = demand_driving.drop(columns=[0,1])

In [34]:
demand_driving

       zone  hour
0      NO03     0
1      NO03     1
2      NO03     2
3      NO03     3
4      NO03     4
...     ...   ...
96355  NO54  8755
96356  NO54  8756
96357  NO54  8757
96358  NO54  8758
96359  NO54  8759

[96360 rows x 2 columns]